### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-ili#1]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by isabelvega1** [comment]
[Diagrama en blanco (1).pdf](https://github.com/aigora/twQ103_2122-ili/files/8450737/Diagrama.en.blanco.1.pdf)

**Comment by lauranbriz** [comment]
[programamenu.md](https://github.com/aigora/twQ103_2122-ili/files/8451280/programamenu.md)
