### ISSUE TITLE
Desarrollo de las principales funciones

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-ili#3]
Debéis implementar las principales funciones del programa.
Esta implementación puede tener cambios en la versión definitiva. Aún no es necesario que realice todas las funcionalidades previstas.
Se recomienda el uso de librerías propias para alojar estas funciones.

**Comment by lauranbriz** [comment]
[Principalesfunciones.md](https://github.com/aigora/twQ103_2122-ili/files/8689296/Principalesfunciones.md)
