### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-ili#4]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by lauranbriz** [comment]
[estructuras1.md](https://github.com/aigora/twQ103_2122-ili/files/8689309/estructuras1.md)

**Comment by lauranbriz** [comment]
[estructuras2.md](https://github.com/aigora/twQ103_2122-ili/files/8689310/estructuras2.md)
