### ISSUE TITLE
Gestión de ficheros

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-ili#5]
Debéis definir el **formato de los ficheros** que vuestro programa genera y lee (por ejemplo, el [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) es muy común para almacenar datos), y debéis **implementar el código** necesario para generar y leer estos ficheros.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by lauranbriz** [comment]
[acertijo1.txt](https://github.com/aigora/twQ103_2122-ili/files/8689313/acertijo1.txt)
[acertijo2.txt](https://github.com/aigora/twQ103_2122-ili/files/8689317/acertijo2.txt)
[acertijo3.txt](https://github.com/aigora/twQ103_2122-ili/files/8689319/acertijo3.txt)
[acertijo4.txt](https://github.com/aigora/twQ103_2122-ili/files/8689320/acertijo4.txt)

**Comment by lauranbriz** [comment]
[ficheros.md](https://github.com/aigora/twQ103_2122-ili/files/8689326/ficheros.md)

**Comment by lauranbriz** [comment]
[bonus.md](https://github.com/aigora/twQ103_2122-ili/files/8689330/bonus.md)
