### ISSUE TITLE
Documentación en wiki

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-ili#7]
Acompañando al código, hay que elaborar la documentación del proyecto. Esta documentación debe estar recogida en la wiki del repositorio.
En el punto de inicio tenéis las [instrucciones](https://github.com/aigora/punto_inicio/wiki/6.-C%C3%B3mo-presentar-el-trabajo) necesarias.
**Debéis cerrar esta issue cuando deis por finalizado el trabajo.**

**Comment by lauranbriz** [comment]
[Wiki.pdf](https://github.com/aigora/twQ103_2122-ili/files/8788983/Wiki.pdf)
