### ISSUE TITLE
Entrega final del código

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-ili#8]
El código del trabajo debe estar completo, sin errores de compilación, y con las funcionalidades descritas en el README y en el diagrama de flujo.

Recordad que:

- Es obligatorio que el trabajo se realice con funciones.
- Es obligatorio utilizar vectores de estructuras.
- Es obligatorio utilizar ficheros.
- Está prohibido el uso de variables globales.

**Debéis cerrar esta issue cuando deis por finalizado el trabajo.**

**Comment by lauranbriz** [comment]
[TRABAJO.md](https://github.com/aigora/twQ103_2122-ili/files/8788952/TRABAJO.md)

**Comment by lauranbriz** [comment]
[acertijo3.txt](https://github.com/aigora/twQ103_2122-ili/files/8788958/acertijo3.txt)
[acertijo4.txt](https://github.com/aigora/twQ103_2122-ili/files/8788961/acertijo4.txt)
[bonus.txt](https://github.com/aigora/twQ103_2122-ili/files/8788965/bonus.txt)


[acertijo2.txt](https://github.com/aigora/twQ103_2122-ili/files/8788957/acertijo2.txt)
[acertijo1.txt](https://github.com/aigora/twQ103_2122-ili/files/8788956/acertijo1.txt)

**Comment by lauranbriz** [comment]
[TRABAJO.md](https://github.com/aigora/twQ103_2122-ili/files/8789019/TRABAJO.md)
